version: '2'

networks:
  graylog.net:

volumes:
  graylog.data.elastic:
    driver: "local"
  graylog.data.mongo:
    driver: "local"

services:
  mongo:
    image: mongo:3
    container_name: mongo
    hostname: mongo
    environment:
      - "TZ=Europe/Amsterdam"
    volumes:
      - graylog.data.mongo:/data/db
    networks:
      - graylog.net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    container_name: elasticsearch
    hostname: graylog.elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      mem_limit: 1g
    volumes:
      - graylog.data.elastic:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "TZ=Europe/Amsterdam"
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    networks:
      - graylog.net
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - graylog.data.elastic:/usr/share/elasticsearch/data
    networks:
      - graylog.net
    ports:
      - "9200:9200"
  graylog:
    image: graylog/graylog:2.4
    hostname: graylog
    environment:
      - "TZ=Europe/Amsterdam"
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://melle4.synology.me:9000/api
      - GRAYLOG_ROOT_TIMEZONE= Europe/Amsterdam
    ports:
      - 9000:9000
      # Syslog UDP
      - 514:514/udp
      # GELF UDP DOCKER
      - 12201:12201/udp
      # GELF UDP MYSQL
      - 12202:12202/udp
      - 12305:12305/udp
      - 5044:5044/udp
    links:
      - mongo
      - elasticsearch
    networks:
      - graylog.net

